### PR TITLE
Issue 13 - Cannot GET / ... on every platform

### PR DESCRIPTION
**Pull request by business-tomcat**
…T / ... on every platform

changed app.html to index.html, so `express.static(app/)` has a valid start page (when used as map server)

### CODE REVIEW

**Review by foucdeg — APPROVED** [review]
Code looks OK, I'll check tomorrow that everything still works.

**Comment by foucdeg** [comment]
@the-business-tomcat I checked the current code with a clean install and found that both the desktop version and mobile access (with the QR code) were functioning correctly, so I couldn't reproduce your problem.

Just to clarify, were you typing `localhost:8080` in your browser? In that case, yes it makes sense that you got "Cannot get /", as the correct URL would look like `http://localhost:8080/app.html?mapServerPort=8080&localIP=localhost`. But your web browser isn't meant to be the main way to look at the map. You're not supposed to need a web browser for this app. 

I'll check in the instructions whether I mentioned that `localhost:8080` is supposed to show something (that may have historically worked fine)

**Comment by foucdeg** [comment]
@the-business-tomcat If you need to view the map in a separate browser, the correct URL is the one encoded in the QR code that you see when you click on the smartphone button (something like `http://localhost:8080/app.html?mapServerPort=8080&localIP=localhost`), because the external browser needs to know which IP and port it should get its plane data from. This information is passed to it via query string parameters. 

In what use case is that unsatisfactory? I can add a clickable link below the QR code to open a browser window on the same computer if that helps.

**Comment by business-tomcat** [comment]
Sry for late answer ...

I never scanned the QR code, because I don't trust QR readers 😉.
So I didn't realize, that the URL to view the map in the browser has `/app.html...`

My use case is also different. I want to use OBS to capture X-Plane with a map overlay. You can use a browser input as capture source, and because the preferences in x-plane-map-electron always told me "port 8080" and so on, it was my assumption just to open `localhost:8080`.

It would be very helpful if you could add the suggested link to open the browser, where I can copy&paste the URL to OBS 😃
Then no need to merge my pull request anymore ... can also remove my fork 😣

**Comment by foucdeg** [comment]
Sounds right, I'll add a copy-pastable URL below the QR code.

**Comment by foucdeg** [comment]
@the-business-tomcat version 2.2.1 has this:

image

How does that look like?

**Pull request closed without merging**
